### PR TITLE
now uses angular 2 and angular-cli

### PR DESCRIPTION
**Pull request by gh0st**
project uses angular 2 and angular-cli for generating `my-app`
there's a problem on `npm start` which throws 

```
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
```

I'll fix it later

### CODE REVIEW

**Comment by gh0st** [comment]
should fix #3 , definitely fixes #2,

**Comment by gh0st** [comment]
actually, if someone could test #3 that'd be awesome.

**Comment by arvindr21** [comment]
@gh0st Thanks for the efforts. But the tutorial what was written on the blog matches the current repo. I don't think so I will be blogging for a few more days hence I am not planning to merge the changes.

Nevertheless, I can add a section in readme, pointing to your fork, incase someone is interested.

**Comment by gh0st** [comment]
Cool! Much appreciated!

**Pull request closed without merging**
